ECHO checking styles
standard "source/**/*.js" --fix

ECHO building sources...
cd tools
mono JavaScriptBundler.exe ../bundleConfig.json
cd ../
ECHO done...

ECHO building packages...
for f in nuget_specs/*.nuspec; do mono tools/nuget.exe pack $f -OutputDirectory nuget_output; done
ECHO done...