@ECHO OFF
ECHO checking styles
call standard "Source/**/*.js" --fix

ECHO building sources...
Tools\JavaScriptBundler.exe bundleConfig.json
ECHO done...

ECHO building packages...
for /r %%x in (*.nuspec) do Tools\nuget.exe pack "%%x" -OutputDirectory nuget_output\
ECHO done...
