ECHO checking styles
standard "Source/**/*.js" --fix

ECHO building sources...
cd Tools
mono JavaScriptBundler.exe ../bundleConfig.json
cd ../
ECHO done...

ECHO building packages...
for f in nuget_specs/*.nuspec; do mono Tools/nuget.exe pack $f -OutputDirectory nuget_output; done
ECHO done...